#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : LibVNCServer
Version  : 0.9.12
Release  : 18
URL      : https://github.com/LibVNC/libvncserver/archive/LibVNCServer-0.9.12.tar.gz
Source0  : https://github.com/LibVNC/libvncserver/archive/LibVNCServer-0.9.12.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: LibVNCServer-lib = %{version}-%{release}
Requires: LibVNCServer-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : gnutls-dev
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libsystemd)
BuildRequires : zlib-dev
Patch1: max-zlib-level.patch
Patch2: lib64.patch
Patch3: CVE-2018-20750.patch
Patch4: CVE-2019-20788.patch

%description
This directory contains a patched Java applet VNC viewer that is SSL
enabled.
The patches in the *.patch files are relative to the source tarball:

%package dev
Summary: dev components for the LibVNCServer package.
Group: Development
Requires: LibVNCServer-lib = %{version}-%{release}
Provides: LibVNCServer-devel = %{version}-%{release}
Requires: LibVNCServer = %{version}-%{release}

%description dev
dev components for the LibVNCServer package.


%package lib
Summary: lib components for the LibVNCServer package.
Group: Libraries
Requires: LibVNCServer-license = %{version}-%{release}

%description lib
lib components for the LibVNCServer package.


%package license
Summary: license components for the LibVNCServer package.
Group: Default

%description license
license components for the LibVNCServer package.


%prep
%setup -q -n libvncserver-LibVNCServer-0.9.12
cd %{_builddir}/libvncserver-LibVNCServer-0.9.12
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1587678126
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1587678126
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/LibVNCServer
cp %{_builddir}/libvncserver-LibVNCServer-0.9.12/COPYING %{buildroot}/usr/share/package-licenses/LibVNCServer/ab8577d3eb0eedf3f98004e381a9cee30e7224e1
cp %{_builddir}/libvncserver-LibVNCServer-0.9.12/webclients/novnc/vendor/pako/LICENSE %{buildroot}/usr/share/package-licenses/LibVNCServer/0ec1c971e17e06db17423a35a9dced8e1531665f
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/rfb/keysym.h
/usr/include/rfb/rfb.h
/usr/include/rfb/rfbclient.h
/usr/include/rfb/rfbconfig.h
/usr/include/rfb/rfbproto.h
/usr/include/rfb/rfbregion.h
/usr/lib64/libvncclient.so
/usr/lib64/libvncserver.so
/usr/lib64/pkgconfig/libvncclient.pc
/usr/lib64/pkgconfig/libvncserver.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libvncclient.so.0.9.12
/usr/lib64/libvncclient.so.1
/usr/lib64/libvncserver.so.0.9.12
/usr/lib64/libvncserver.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/LibVNCServer/0ec1c971e17e06db17423a35a9dced8e1531665f
/usr/share/package-licenses/LibVNCServer/ab8577d3eb0eedf3f98004e381a9cee30e7224e1
