#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libvncserver
Version  : 0.9.10
Release  : 1
URL      : https://github.com/LibVNC/libvncserver/archive/LibVNCServer-0.9.10.tar.gz
Source0  : https://github.com/LibVNC/libvncserver/archive/LibVNCServer-0.9.10.tar.gz
Summary  : A library for easy implementation of a VNC server.
Group    : Development/Tools
License  : GPL-2.0
Requires: libvncserver-bin
Requires: libvncserver-lib
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(gtk+-2.0)

%description
LibVNCServer: A library for easy implementation of a VNC server.
If you already used LibVNCServer, you probably want to read NEWS.

%package bin
Summary: bin components for the libvncserver package.
Group: Binaries

%description bin
bin components for the libvncserver package.


%package dev
Summary: dev components for the libvncserver package.
Group: Development
Requires: libvncserver-lib
Requires: libvncserver-bin
Provides: libvncserver-devel

%description dev
dev components for the libvncserver package.


%package lib
Summary: lib components for the libvncserver package.
Group: Libraries

%description lib
lib components for the libvncserver package.


%prep
%setup -q -n libvncserver-LibVNCServer-0.9.10

%build
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/libvncserver-config

%files dev
%defattr(-,root,root,-)
/usr/include/rfb/keysym.h
/usr/include/rfb/rfb.h
/usr/include/rfb/rfbclient.h
/usr/include/rfb/rfbconfig.h
/usr/include/rfb/rfbint.h
/usr/include/rfb/rfbproto.h
/usr/include/rfb/rfbregion.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
